### ISSUE TITLE
Error installing on RPI Zero

### ISSUE THREAD

**Issue by dcasado** [etesync/etebase-py#23]
Hi!

I'm trying to install etebase-py in a Raspberry Pi Zero W with `pip install etebase` but after long time compiling it threw the next error.

Python version: 3.7.3
rustc version: 1.49.0 (e1884a8e3 2020-12-29)
cargo version: 1.49.0 (d00d64df9 2020-12-05)

etebase-py version: 0.31.2

```
Compiling etebase-python v0.31.2 (/tmp/pip-install-aa2p737k/etebase)
       Running `rustc --crate-name etebase_python --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type cdylib --emit=dep-info,link -C opt-level=3 -C embed-bitcode
=no --crate-type cdylib -C metadata=b2d6ba32175a0e19 --out-dir /tmp/pip-install-aa2p737k/etebase/target/release/deps -L dependency=/tmp/pip-install-aa2p737k/etebase/target/release/deps --extern cpytho
n=/tmp/pip-install-aa2p737k/etebase/target/release/deps/libcpython-8e18579c49af6fa0.rlib --extern etebase=/tmp/pip-install-aa2p737k/etebase/target/release/deps/libetebase-deea0702211d47fe.rlib --exter
n openssl=/tmp/pip-install-aa2p737k/etebase/target/release/deps/libopenssl-a8abac1f33fcb9d4.rlib -L native=/tmp/pip-install-aa2p737k/etebase/target/release/build/libsodium-sys-978ee12a069c8072/out/ins
talled/lib -L native=/tmp/pip-install-aa2p737k/etebase/target/release/build/openssl-sys-951a470f70f3156f/out/openssl-build/install/lib`
  error: environment variable `OUT_DIR` not defined
    --> src/lib.rs:62:18
     |
  62 | include!(concat!(env!("OUT_DIR"), "/glue.rs"));
     |                  ^^^^^^^^^^^^^^^
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: aborting due to previous error

  error: could not compile `etebase-python`

  Caused by:
    process didn't exit successfully: `rustc --crate-name etebase_python --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type cdylib --emit=dep-info,link -C opt-l
evel=3 -C embed-bitcode=no --crate-type cdylib -C metadata=b2d6ba32175a0e19 --out-dir /tmp/pip-install-aa2p737k/etebase/target/release/deps -L dependency=/tmp/pip-install-aa2p737k/etebase/target/relea
se/deps --extern cpython=/tmp/pip-install-aa2p737k/etebase/target/release/deps/libcpython-8e18579c49af6fa0.rlib --extern etebase=/tmp/pip-install-aa2p737k/etebase/target/release/deps/libetebase-deea07
02211d47fe.rlib --extern openssl=/tmp/pip-install-aa2p737k/etebase/target/release/deps/libopenssl-a8abac1f33fcb9d4.rlib -L native=/tmp/pip-install-aa2p737k/etebase/target/release/build/libsodium-sys-9
78ee12a069c8072/out/installed/lib -L native=/tmp/pip-install-aa2p737k/etebase/target/release/build/openssl-sys-951a470f70f3156f/out/openssl-build/install/lib` (exit code: 1)
  error: cargo failed with code: 101


  ----------------------------------------
  Failed building wheel for etebase
```

I know nothing about rust so any help would be appreciated.

**Comment by tasn** [comment]
If I had to guess, it looks like a bug in Rust unstable (which you seem to be using) as this is a very standard env var in cargo build.
To be honest, we should be offering armv7 packages... See related ticket: #24

**Comment by dcasado** [comment]
I tried with one version older of rustc and cargo (1.48.0) but the same error happened. Could you point me to a recommended version to try to build it with? Thank you!

**Comment by tasn** [comment]
I use 1.48.0, so I guess it's not an issue with rust or cargo.
Looks similar to https://github.com/lalrpop/lalrpop/issues/427#issuecomment-446386054
Could you maybe try building the etebase-py python package separately rather than through pip? I wonder if that will fix it.
Just `python setup.py build`

**Comment by dcasado** [comment]
You were right! I built it with `python setup.py build` and then used `python setup.py install` to set it up in site_packages folder. After that I had to change the name of the so file from `etebase_python.cpython-37m-arm-linux-gnueabihf.so` to `etebase_python.so`. Now I can at least import the module in my python script. I will try to use more functionality tomorrow and see if everything works.

Thanks for your help!

**Comment by tasn** [comment]
With pleasure! Weird that you need to rename it, but good to know!

**Comment by dcasado** [comment]
So far so good. I tried getting events of a calendar and everything worked perfectly fine. I would love to see arm packages compatible with the Raspberry in the future to avoid this trouble but it works like a charm. Thanks!

**Comment by tasn** [comment]
Yeah, I'd love it too. The Python build env we use (cibuildwheel) doesn't support basic (non 64 bit) arm for some reason.
