### ISSUE TITLE
Release python3.10 version to pip

### ISSUE THREAD

**Issue by Salt-Factory** [etesync/etebase-py#25]
Since the Python3.10 update, etesync-dav no longer works.
After reinstalling the dav from the AUR, I get the following error:

```
$ etesync-dav
Traceback (most recent call last):
  File "/usr/bin/etesync-dav", line 10, in <module>
    from etesync_dav.manage import Manager
  File "/usr/lib/python3.10/site-packages/etesync_dav/manage.py", line 22, in <module>
    import etebase as Etebase
ModuleNotFoundError: No module named 'etebase'
```

Installing etebase from pip results in an error in the rust compilation.

**Comment by Salt-Factory** [comment]
Temporary workaround: install `python-etebase` from the AUR.

**Comment by tasn** [comment]
Build triggered now, let's wait. :)

**Comment by tasn** [comment]
https://github.com/etesync/etebase-py/actions/runs/1598335712

**Comment by Salt-Factory** [comment]
Thanks tasn!
