### ISSUE TITLE
etebase-python-0.31.4-3 from Arch AUR fails to compile

### ISSUE THREAD

**Issue by downtrip** [etesync/etebase-py#26]
Hi, I get this error when trying to compile etebase-python-0.31.4-3 from Arch AUR:

fetching devel info...
==> Making package: python-etebase 0.31.4-3 (Sun 19 Dec 2021 20:16:44 GMT)
==> Retrieving sources...
  -> Cloning python-etebase git repo...
Cloning into bare repository '/home/chuckie/.cache/paru/clone/python-etebase/python-etebase'...
remote: Enumerating objects: 1590, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 1590 (delta 11), reused 29 (delta 10), pack-reused 1559
Receiving objects: 100% (1590/1590), 283.00 KiB | 3.33 MiB/s, done.
Resolving deltas: 100% (958/958), done.
  -> Found 0001-Dynamically-link-against-libssl.patch
==> Validating source files with sha512sums...
    python-etebase ... Skipped
    0001-Dynamically-link-against-libssl.patch ... Skipped
==> Making package: python-etebase 0.31.4-3 (Sun 19 Dec 2021 20:16:45 GMT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating python-etebase git repo...
Fetching origin
  -> Found 0001-Dynamically-link-against-libssl.patch
==> Validating source files with sha512sums...
    python-etebase ... Skipped
    0001-Dynamically-link-against-libssl.patch ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of python-etebase git repo...
Cloning into 'python-etebase'...
done.
Switched to a new branch 'makepkg'
==> Starting prepare()...
error: patch failed: Cargo.toml:19
error: Cargo.toml: patch does not apply
==> ERROR: A failure occurred in prepare().
    Aborting...
error: failed to build 'python-etebase-0.31.4-3':

FWIW openssl was upgraded on my box yesterday 1.1.1.l-1 -> 1.1.1.m-1 - not sure if the libssl.patch is affected by that

**Comment by tasn** [comment]
Nah, it's my bad. One sec.

**Comment by tasn** [comment]
Try now.

**Comment by downtrip** [comment]
Perfect, thanks
